# Generated by Django 2.0 on 2018-01-23 22:15

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='_text_rendered',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deadline',
            name='text_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown')], default='markdown', max_length=30),
        ),
        migrations.AddField(
            model_name='material',
            name='_text_rendered',
            field=models.TextField(default='some opt', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='text_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown')], default='markdown', max_length=30),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='text',
            field=markupfield.fields.MarkupField(rendered_field=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='material',
            name='text',
            field=markupfield.fields.MarkupField(rendered_field=True, verbose_name='name'),
        ),
    ]
