# Generated by Django 2.0 on 2018-01-27 10:30

from django.db import migrations, models
import homework.models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_auto_20180127_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=homework.models.update_filename),
        ),
    ]
