# Generated by Django 2.0 on 2018-01-30 14:41

from django.db import migrations
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0006_auto_20180127_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='text',
            field=markupfield.fields.MarkupField(rendered_field=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='material',
            name='text',
            field=markupfield.fields.MarkupField(rendered_field=True, verbose_name='text'),
        ),
    ]
